### ISSUE TITLE
Automation Script for MOHS Dashboard Data 

### ISSUE THREAD

**Issue by nyanlynntherazi** [theananda/data#5]
To write automation script to handle MOHS dashboard data

**Comment by AungKhantThaw47** [comment]
How about uploading new data directly on web api
UIT SU team is now developing an api service

**Comment by nyanlynntherazi** [comment]
We are happy to push directly to web API if there's one available but still need to archive properly here since non technical persons are also using the data as well. Let us know when you finish setting up your API. We will help anything we can and we would like to list the API [here](https://github.com/nyanlynntherazi/awesome-myanmar-covid19-resources) too.

**Comment by nyanlynntherazi** [comment]
Repository moved to new [location](https://github.com/theananda/myanmar-covid19-data/). Issue has been reopened in new repository.
